services:
  messaging-broker:
    container_name: microservices-messaging-broker-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  observability-jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # Traces UDP
      - "14268:14268" # Traces HTTP
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP

  api-gateway-kong:
    image: kong:3.9
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_DECLARATIVE_CONFIG: "/kong/config.yaml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/kong/config.yaml:/kong/config.yaml
    ports:
      - "8003:8003" # Proxy (API) Default 8000
      - "8001:8001" # API ADMIN
      - "8002:8002" # UI ADMIN
      - "8443:8442" # Proxy SSL (HTTPs)
      - "8444:8444" # API (Admin) (HTTPs)

volumes:
  rabbitmq_data:
