services:
  postgres:
    container_name: microservices-invoices-postgres
    image: bitnami/postgresql:latest
    ports:
      - "5483:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=microservices-invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
