_format_version: "3.0"
_transform: true


services:
  - name: orders
    url: http://host.docker.internal:3333
    protocol: http
    port: 3333
    path: /orders

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Acecpts
        - Contenty-Type
        - Authorization